name = "ManagedLoops"
uuid = "36a4119d-6b73-4371-88fe-ba2d91f5495d"
authors = ["Thomas Dubos <thomas.dubos@lmd.ipsl.fr>"]
version = "0.1.11"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"

[extensions]
ManagedLoopsAdaptExt = ["Adapt"]

[compat]
Adapt = "2, 3, 4"
MacroTools = "0.5.7"
PackageExtensionCompat = "1"
julia = "1.8"

[extras]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
