name = "ManagedLoops"
uuid = "36a4119d-6b73-4371-88fe-ba2d91f5495d"
authors = ["Thomas Dubos <thomas.dubos@lmd.ipsl.fr>"]
version = "0.1.4"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MutatingOrNot = "6a37069a-9a67-4b2d-a34a-f09ab4b23c7c"

[compat]
MacroTools = "0.5.7"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
